### ISSUE TITLE
"Press Enter / Return key" doesn't wait for input

### ISSUE THREAD

**Issue by fosskers** [Rikoru/passgen#1]
Both when doing everything correctly and when exceeding the max attempts number, `Press Enter / Return key` is displayed, but the program exits without waiting for input.

**Comment by Rikoru** [comment]
I'll get on that, thanks for bringing this to my attention.

**Comment by Rikoru** [comment]
Fixed with commit 5760654ef35c54cf37cd3dccd4d5cf39d2713f76
