### ISSUE TITLE
[Suggestion] Print generated passwords to `stdout`

### ISSUE THREAD

**Issue by fosskers** [Rikoru/passgen#2]
At which point a user wanting them in a file could just use an output redirect:

```
pass --n=10 > passwords.txt
```

where `--n` indicates the number of passwords to generate. If there was no other output other than the passwords, then the results could easily be piped to other programs.

**Comment by Rikoru** [comment]
This is a good idea, I'll see what I can do.

**Comment by Rikoru** [comment]
Made a branch for it and got it working: b43213e77147207560261a20f43a49a44260aaa0

**Comment by Rikoru** [comment]
Functionality now exists. Properly implemented into master.

**Comment by fosskers** [comment]
Cool.
